# training/trainer.py
class Trainer:
    def __init__(self, model, optimizer, loss_fn, device, config): ...
    def train_epoch(self, train_loader): # -> avg_loss
        # Loop through batches, call model.forward, calculate loss, backpropagate
        ...
    def evaluate(self, val_loader): # -> metrics_dict
        # Evaluate model on validation set
        ...
    def train(self, train_loader, val_loader, num_epochs): # -> training_history
        # Main training loop
        ...